"""
Frozen asymmetry/symmetry labels for binary relations in FOLIO.

Source pools:
  - severity_correlation design pool (128 premises)
  - perturbation_detection reference pool (642 premises, disjoint)
  Union: 770 premises; 427 unique binary predicates (excluding ``__eq__``).

Labels:
  - "asymmetric" — inject ``∀x,y.P(x,y) → ¬P(y,x)`` as a witness axiom
    in swap_binary_args admissibility. Lets Vampire certify the swapped
    formula as incompatible, admitting the contrastive.
  - "symmetric" — inject ``∀x,y.P(x,y) → P(y,x)``. Makes the swap
    entailment-neutral, correctly keeping the contrastive inadmissible.
  - "unknown" — inject no axiom. Behavior unchanged from default
    (contrastive likely dropped).

Methodology: each predicate name was inspected against representative
FOLIO usages (NL gloss + gold FOL). Labels assigned by examining
semantic directionality. Conservative bias toward "unknown" when
genuinely ambiguous, because a mislabeled "symmetric" predicate
risks unsound admissibility, while a mislabeled "unknown" merely
forfeits the recall gain.

Strict asymmetry (``R(x,y) → ¬R(y,x)``) forbids self-loops
``R(x,x)``. The spec accepts this; FOLIO does not have premises
that depend on reflexive readings of the predicates labeled here.

DO NOT add predicates to this table after the diagnostic-trace
experiment has been scored. Predicates encountered post-freeze that
aren't in the table are treated as "unknown" via ``get_label`` and
logged for post-hoc inspection.
"""
from __future__ import annotations

from typing import Literal, Optional


Label = Literal["asymmetric", "symmetric", "unknown"]


# ── Frozen table ─────────────────────────────────────────────────────────────
# Generated by inspecting siv/contrastive_generator + the union of the
# severity_correlation design pool and the perturbation_detection
# reference pool. 427 entries. Comments show usage counts across the
# union pool (770 premises).

ASYMMETRY_LABELS: dict[str, Label] = {
    'ACRate': 'asymmetric',  # count=1
    'About': 'asymmetric',  # count=4
    'AcquiredBy': 'asymmetric',  # count=1
    'Adapted': 'asymmetric',  # count=1
    'AddictedTo': 'asymmetric',  # count=2
    'AdjacentWalls': 'symmetric',  # count=1
    'AdministrativeCenterOf': 'asymmetric',  # count=1
    'Admit': 'asymmetric',  # count=1
    'Affect': 'asymmetric',  # count=1
    'Age': 'unknown',  # count=1
    'AirOn': 'asymmetric',  # count=1
    'AiredOn': 'asymmetric',  # count=1
    'AlbumByBand': 'asymmetric',  # count=1
    'Analyze': 'asymmetric',  # count=1
    'Apply': 'asymmetric',  # count=2
    'ApprovedFor': 'asymmetric',  # count=1
    'AssociatedWith': 'asymmetric',  # count=1
    'At': 'asymmetric',  # count=17
    'Attend': 'asymmetric',  # count=4
    'AttendFrequently': 'asymmetric',  # count=1
    'AttendInPerson': 'asymmetric',  # count=2
    'AttendRegularly': 'asymmetric',  # count=2
    'Attended': 'asymmetric',  # count=1
    'AttendedSchoolIn': 'asymmetric',  # count=1
    'Attending': 'asymmetric',  # count=2
    'Attract': 'asymmetric',  # count=1
    'Authored': 'asymmetric',  # count=1
    'AwardedTo': 'asymmetric',  # count=1
    'AwareThatDrug': 'asymmetric',  # count=1
    'Bad': 'unknown',  # count=1
    'BadAt': 'asymmetric',  # count=4
    'BasedIn': 'asymmetric',  # count=1
    'BasedOn': 'asymmetric',  # count=1
    'BeHeldIn': 'asymmetric',  # count=1
    'Become': 'asymmetric',  # count=1
    'Before': 'asymmetric',  # count=1
    'BelieveIn': 'asymmetric',  # count=3
    'BelongTo': 'asymmetric',  # count=3
    'Better': 'unknown',  # count=1
    'BittenBy': 'asymmetric',  # count=1
    'BookedDuring': 'asymmetric',  # count=1
    'BookedIn': 'asymmetric',  # count=2
    'Born': 'asymmetric',  # count=1
    'BornIn': 'asymmetric',  # count=6
    'BornOn': 'asymmetric',  # count=1
    'Borrow': 'asymmetric',  # count=1
    'Breaks': 'asymmetric',  # count=1
    'Broke': 'asymmetric',  # count=1
    'BuiltBy': 'asymmetric',  # count=2
    'BuiltFor': 'asymmetric',  # count=2
    'BusyWith': 'asymmetric',  # count=2
    'Buy': 'asymmetric',  # count=1
    'By': 'asymmetric',  # count=3
    'CameraAccessoryFor': 'asymmetric',  # count=3
    'Camping': 'asymmetric',  # count=2
    'Can': 'asymmetric',  # count=5
    'CanArgueAgainst': 'asymmetric',  # count=1
    'CanBeConnectedTo': 'asymmetric',  # count=2
    'CanCatch': 'asymmetric',  # count=1
    'CanCatchWith': 'asymmetric',  # count=1
    'CanControl': 'asymmetric',  # count=3
    'CanHavePartiallyCovered': 'asymmetric',  # count=1
    'CanInjure': 'asymmetric',  # count=1
    'CanMake': 'asymmetric',  # count=3
    'CanStandOnTheGround': 'asymmetric',  # count=1
    'CanTake': 'asymmetric',  # count=1
    'CanTurnInto': 'asymmetric',  # count=1
    'CapitalOf': 'asymmetric',  # count=1
    'Cares': 'asymmetric',  # count=1
    'Carry': 'asymmetric',  # count=2
    'CheaperThan': 'asymmetric',  # count=1
    'Choose': 'asymmetric',  # count=1
    'ChooseWhatToDoWith': 'asymmetric',  # count=1
    'ClassroomIn': 'asymmetric',  # count=5
    'Clear': 'unknown',  # count=1
    'Coach': 'asymmetric',  # count=1
    'Colony': 'asymmetric',  # count=1
    'ComeToWorkWithEveryDay': 'asymmetric',  # count=1
    'CompatibleWith': 'asymmetric',  # count=1
    'CompeteIn': 'asymmetric',  # count=2
    'ConnectTo': 'asymmetric',  # count=1
    'ConnectedTo': 'unknown',  # count=3
    'ConsidersMostImportantLoveLanguage': 'asymmetric',  # count=1
    'Contain': 'asymmetric',  # count=7
    'ContributeTo': 'asymmetric',  # count=1
    'ControlledBy': 'asymmetric',  # count=2
    'Convey': 'asymmetric',  # count=1
    'Cover': 'asymmetric',  # count=1
    'Creates': 'asymmetric',  # count=1
    'DaughterOf': 'asymmetric',  # count=1
    'Debut': 'asymmetric',  # count=1
    'Defeat': 'asymmetric',  # count=1
    'Designed': 'asymmetric',  # count=2
    'DesignedBy': 'asymmetric',  # count=2
    'DesignedFor': 'asymmetric',  # count=1
    'Develop': 'asymmetric',  # count=2
    'Develops': 'asymmetric',  # count=1
    'Directed': 'asymmetric',  # count=1
    'DirectedBy': 'asymmetric',  # count=2
    'DisbandsIn': 'asymmetric',  # count=1
    'DiscoversIn': 'asymmetric',  # count=1
    'DisplayedIn': 'asymmetric',  # count=2
    'DistrictIn': 'asymmetric',  # count=2
    'DriveTo': 'asymmetric',  # count=1
    'DrinkRegularly': 'asymmetric',  # count=2
    'EditedBy': 'asymmetric',  # count=1
    'EmigratedTo': 'asymmetric',  # count=1
    'EmployeeIn': 'asymmetric',  # count=5
    'EnglishClassScore': 'asymmetric',  # count=1
    'EnglishScore': 'asymmetric',  # count=3
    'Enjoy': 'asymmetric',  # count=8
    'EnjoyEating': 'asymmetric',  # count=2
    'EnjoyRegularly': 'asymmetric',  # count=1
    'EnjoyVisiting': 'asymmetric',  # count=1
    'EnjoyWatching': 'asymmetric',  # count=2
    'EnrolledIn': 'asymmetric',  # count=1
    'EntitledTo': 'asymmetric',  # count=5
    'EntraceTo': 'asymmetric',  # count=1
    'Equals': 'symmetric',  # count=1
    'EquippedWith': 'asymmetric',  # count=1
    'EquippedWithSeats': 'asymmetric',  # count=1
    'EssentialFor': 'asymmetric',  # count=1
    'Established': 'asymmetric',  # count=1
    'EstablishedBy': 'asymmetric',  # count=1
    'EstablishedIn': 'asymmetric',  # count=2
    'ExcitedFor': 'asymmetric',  # count=2
    'ExecutiveProducerOf': 'asymmetric',  # count=1
    'ExposedTo': 'asymmetric',  # count=1
    'Failed': 'unknown',  # count=2
    'FamousIn': 'asymmetric',  # count=1
    'Favor': 'asymmetric',  # count=2
    'Favorite': 'asymmetric',  # count=2
    'FederalDistrictOf': 'asymmetric',  # count=2
    'FewerGoldMedalsThan': 'asymmetric',  # count=1
    'FightIn': 'asymmetric',  # count=1
    'FilmedIn': 'asymmetric',  # count=1
    'Finding': 'asymmetric',  # count=1
    'FinishesIn': 'asymmetric',  # count=1
    'FirstDinnerPartyFor': 'asymmetric',  # count=1
    'FlowsTo': 'asymmetric',  # count=1
    'FlyOver': 'asymmetric',  # count=3
    'FlyTo': 'asymmetric',  # count=2
    'FocusedOn': 'asymmetric',  # count=1
    'FondOf': 'asymmetric',  # count=2
    'Following': 'unknown',  # count=1
    'Form': 'asymmetric',  # count=1
    'FormerMemberOf': 'asymmetric',  # count=1
    'FoundationOf': 'asymmetric',  # count=1
    'From': 'asymmetric',  # count=11
    'FromAndTo': 'unknown',  # count=1
    'Genre': 'unknown',  # count=1
    'Genus': 'unknown',  # count=1
    'Get': 'asymmetric',  # count=1
    'GetAJobAt': 'asymmetric',  # count=2
    'GetAlongWithAtWork': 'asymmetric',  # count=1
    'GoTo': 'asymmetric',  # count=9
    'GoToEveryWeek': 'asymmetric',  # count=1
    'GoodAt': 'asymmetric',  # count=11
    'GoodAtPlaying': 'asymmetric',  # count=1
    'Graduated': 'asymmetric',  # count=1
    'GraduatedWith': 'asymmetric',  # count=1
    'GreaterThan': 'asymmetric',  # count=1
    'GrowUpWith': 'asymmetric',  # count=1
    'GrownIn': 'asymmetric',  # count=4
    'HandbrakeOf': 'asymmetric',  # count=2
    'Has': 'asymmetric',  # count=4
    'HasLogo': 'asymmetric',  # count=2
    'Hate': 'asymmetric',  # count=1
    'HateWorkingFor': 'asymmetric',  # count=2
    'Have': 'asymmetric',  # count=21
    'HaveAnACRateLowerThan': 'asymmetric',  # count=2
    'HaveEnoughMoneyFor': 'asymmetric',  # count=2
    'HaveTemporaryRoleAt': 'asymmetric',  # count=3
    'HeldIn': 'asymmetric',  # count=1
    'Help': 'asymmetric',  # count=1
    'HelpSlowDown': 'asymmetric',  # count=1
    'Higher': 'unknown',  # count=1
    'HigherRank': 'asymmetric',  # count=2
    'HigherThan': 'asymmetric',  # count=2
    'HighlyAcclaimedIn': 'asymmetric',  # count=2
    'Hire': 'asymmetric',  # count=1
    'Holds': 'unknown',  # count=1
    'Hometown': 'unknown',  # count=1
    'HostShowOn': 'asymmetric',  # count=1
    'IdealFor': 'asymmetric',  # count=2
    'In': 'asymmetric',  # count=84
    'InjuredAt': 'asymmetric',  # count=1
    'InstrumentalIn': 'asymmetric',  # count=1
    'IntendedToBeDrivenAt': 'asymmetric',  # count=2
    'InterestedIn': 'asymmetric',  # count=1
    'InvestIn': 'asymmetric',  # count=2
    'InvestInRegularly': 'asymmetric',  # count=1
    'InvestedIn': 'asymmetric',  # count=1
    'InvestigatePersonally': 'asymmetric',  # count=1
    'InvitedToJoin': 'asymmetric',  # count=2
    'InvitedToTakePhotoWith': 'asymmetric',  # count=1
    'InvolvedIn': 'asymmetric',  # count=2
    'Is': 'unknown',  # count=1
    'IsAlbumOf': 'asymmetric',  # count=1
    'IsDependentOn': 'asymmetric',  # count=1
    'IsDouble': 'asymmetric',  # count=1
    'IsSpecies': 'asymmetric',  # count=1
    'IssuedBy': 'asymmetric',  # count=2
    'Joined': 'asymmetric',  # count=1
    'Know': 'asymmetric',  # count=4
    'KnownSpeciesOf': 'asymmetric',  # count=1
    'Knows': 'asymmetric',  # count=3
    'LargestCityOf': 'asymmetric',  # count=1
    'LastLonger': 'asymmetric',  # count=1
    'LaunchedBy': 'asymmetric',  # count=1
    'LeadSinger': 'asymmetric',  # count=1
    'LeadSingleOf': 'asymmetric',  # count=1
    'LeadTo': 'asymmetric',  # count=1
    'LeaveOut': 'asymmetric',  # count=1
    'LessThan': 'asymmetric',  # count=1
    'Like': 'asymmetric',  # count=6
    'LikeEating': 'asymmetric',  # count=1
    'LikeShoppingFor': 'asymmetric',  # count=1
    'Liked': 'asymmetric',  # count=1
    'LitProductions': 'asymmetric',  # count=1
    'LiveIn': 'asymmetric',  # count=11
    'LiveWith': 'asymmetric',  # count=1
    'LocatedIn': 'asymmetric',  # count=5
    'LocatedOn': 'asymmetric',  # count=2
    'Locatedin': 'asymmetric',  # count=3
    'Lost': 'unknown',  # count=2
    'Love': 'asymmetric',  # count=3
    'Loves': 'asymmetric',  # count=2
    'MadeBy': 'asymmetric',  # count=1
    'MadeIn': 'asymmetric',  # count=3
    'MadeOf': 'asymmetric',  # count=3
    'MainCharacterOf': 'asymmetric',  # count=1
    'MakeMeal': 'asymmetric',  # count=1
    'ManagedBy': 'asymmetric',  # count=3
    'Managedby': 'asymmetric',  # count=1
    'Mangedby': 'asymmetric',  # count=1
    'MeansToDestination': 'asymmetric',  # count=1
    'Measure': 'asymmetric',  # count=2
    'Member': 'unknown',  # count=1
    'MemberOf': 'asymmetric',  # count=3
    'MorePoints': 'asymmetric',  # count=1
    'MorePointsInGameBetween': 'asymmetric',  # count=1
    'MoreThan': 'asymmetric',  # count=5
    'Named': 'asymmetric',  # count=3
    'NativeTo': 'asymmetric',  # count=1
    'Near': 'symmetric',  # count=2 (proximity is conventionally symmetric)
    'NearlySphericalShape': 'asymmetric',  # count=1
    'Need': 'asymmetric',  # count=2
    'NeedToBeWrittenWith': 'asymmetric',  # count=1
    'NeedToSave': 'asymmetric',  # count=3
    'OfficeIn': 'asymmetric',  # count=1
    'Older': 'asymmetric',  # count=1
    'OlderThan': 'asymmetric',  # count=1
    'On': 'asymmetric',  # count=3
    'OperatedBy': 'asymmetric',  # count=1
    'Opposed': 'asymmetric',  # count=1
    'OrbitOf': 'asymmetric',  # count=1
    'OrderAtLeastOnceADay': 'asymmetric',  # count=1
    'OrderOften': 'asymmetric',  # count=2
    'Outside': 'asymmetric',  # count=2
    'Oversee': 'asymmetric',  # count=1
    'Own': 'asymmetric',  # count=4
    'OwnedBy': 'asymmetric',  # count=6
    'Owns': 'asymmetric',  # count=3
    'PaintedBy': 'asymmetric',  # count=1
    'ParentOf': 'asymmetric',  # count=3
    'PartOf': 'asymmetric',  # count=3
    'ParticipatedIn': 'asymmetric',  # count=1
    'Peak': 'unknown',  # count=1
    'PerformAt': 'asymmetric',  # count=5
    'PermanentMemberOf': 'asymmetric',  # count=2
    'PetOf': 'asymmetric',  # count=1
    'Placed': 'asymmetric',  # count=1
    'PlacedSecondInGoldMedalsIn': 'asymmetric',  # count=1
    'PlansToApplyTo': 'asymmetric',  # count=1
    'Play': 'asymmetric',  # count=6
    'PlayedAs': 'asymmetric',  # count=1
    'PlaysIn': 'asymmetric',  # count=1
    'PlaysOften': 'asymmetric',  # count=2
    'PlotsToSwallowUp': 'asymmetric',  # count=1
    'PopularAt': 'asymmetric',  # count=2
    'Popularize': 'asymmetric',  # count=1
    'Population': 'unknown',  # count=1
    'PoseRiskTo': 'asymmetric',  # count=1
    'Practice': 'asymmetric',  # count=1
    'PrecededBy': 'asymmetric',  # count=2
    'Prefer': 'asymmetric',  # count=6
    'Prereq': 'asymmetric',  # count=3
    'PresentWorkAt': 'asymmetric',  # count=2
    'PresidedOver': 'asymmetric',  # count=1
    'Prevent': 'asymmetric',  # count=1
    'Produce': 'asymmetric',  # count=2
    'ProducedAfterNewCTOAppointed': 'asymmetric',  # count=1
    'ProducedBefore': 'asymmetric',  # count=2
    'ProducedBy': 'asymmetric',  # count=2
    'ProducedIn': 'asymmetric',  # count=3
    'Produces': 'asymmetric',  # count=1
    'ProductOf': 'asymmetric',  # count=1
    'ProfessorEmeritusAt': 'asymmetric',  # count=1
    'PromotedTo': 'asymmetric',  # count=1
    'ProsecuteInAppropriateCourt': 'asymmetric',  # count=1
    'Provide': 'asymmetric',  # count=3
    'ProvedToBe': 'asymmetric',  # count=1
    'ProvidedWith': 'asymmetric',  # count=3
    'Provides': 'asymmetric',  # count=1
    'Publish': 'asymmetric',  # count=1
    'PublishedAfter': 'asymmetric',  # count=2
    'PublishedBy': 'asymmetric',  # count=1
    'PursuedBy': 'asymmetric',  # count=1
    'PutEmotionInto': 'asymmetric',  # count=1
    'RankHigherThan': 'asymmetric',  # count=1
    'Ranked': 'asymmetric',  # count=1
    'RankedBy': 'asymmetric',  # count=1
    'ReadBy': 'asymmetric',  # count=2
    'RecommendedTo': 'asymmetric',  # count=2
    'Regret': 'asymmetric',  # count=1
    'Released': 'asymmetric',  # count=1
    'ReleasedAlbum': 'asymmetric',  # count=1
    'ReleasedBy': 'asymmetric',  # count=2
    'Rent': 'asymmetric',  # count=1
    'Request': 'asymmetric',  # count=1
    'Require': 'asymmetric',  # count=1
    'RequiredFor': 'asymmetric',  # count=1
    'Residentof': 'asymmetric',  # count=1
    'Resist': 'asymmetric',  # count=1
    'ResultOf': 'asymmetric',  # count=1
    'RetiredIn': 'asymmetric',  # count=1
    'ReturnedBy': 'asymmetric',  # count=1
    'RewardWith': 'asymmetric',  # count=2
    'RockBand': 'asymmetric',  # count=1
    'RoomFor': 'asymmetric',  # count=1
    'Run': 'unknown',  # count=1
    'SameCountry': 'symmetric',  # count=1
    'SameScore': 'symmetric',  # count=2
    'SatIn': 'asymmetric',  # count=1
    'ScaredOf': 'asymmetric',  # count=1
    'ScheduledFor': 'asymmetric',  # count=1
    'ScoredOver': 'asymmetric',  # count=2
    'ScratchedBy': 'asymmetric',  # count=1
    'See': 'asymmetric',  # count=1
    'ServeIn': 'asymmetric',  # count=1
    'ServeWith': 'asymmetric',  # count=1
    'ServedAs': 'asymmetric',  # count=1
    'ServedIn': 'asymmetric',  # count=1
    'ServesIn': 'asymmetric',  # count=1
    'SetIn': 'asymmetric',  # count=1
    'ShippedFrom': 'asymmetric',  # count=3
    'ShowRunnerOf': 'asymmetric',  # count=1
    'Simulate': 'asymmetric',  # count=2
    'Sleep': 'unknown',  # count=1
    'Smoother': 'asymmetric',  # count=1
    'Sold': 'asymmetric',  # count=2
    'SoldAs': 'asymmetric',  # count=1
    'SoldAt': 'asymmetric',  # count=1
    'SoldCopies': 'asymmetric',  # count=3
    'SoldIn': 'asymmetric',  # count=7
    'SonOf': 'asymmetric',  # count=1
    'Speak': 'asymmetric',  # count=2
    'SpecializeInPerformanceOf': 'asymmetric',  # count=1
    'SpecializesIn': 'asymmetric',  # count=1
    'Spend': 'asymmetric',  # count=1
    'SpendFrivolously': 'asymmetric',  # count=1
    'Start': 'unknown',  # count=1
    'StarredByMoreThan': 'asymmetric',  # count=4
    'StartPastNoonRegularly': 'asymmetric',  # count=2
    'StateOf': 'asymmetric',  # count=2
    'StealsFundsInYr': 'asymmetric',  # count=1
    'StickTo': 'asymmetric',  # count=2
    'Sting': 'asymmetric',  # count=1
    'StrikeInCity': 'asymmetric',  # count=1
    'StrikeInMo': 'asymmetric',  # count=1
    'StrikeInYr': 'asymmetric',  # count=1
    'StudyIn': 'asymmetric',  # count=1
    'SubscribedTo': 'asymmetric',  # count=4
    'SummerOlympicsIn': 'asymmetric',  # count=1
    'SunAs': 'asymmetric',  # count=1
    'Support': 'asymmetric',  # count=5
    'Supported': 'asymmetric',  # count=1
    'Take': 'asymmetric',  # count=3
    'Teach': 'asymmetric',  # count=1
    'ThinkMadeUp': 'asymmetric',  # count=2
    'Titled': 'asymmetric',  # count=1
    'TransferredTo': 'asymmetric',  # count=1
    'TravelingFrom': 'asymmetric',  # count=2
    'TravelingTo': 'asymmetric',  # count=2
    'Treat': 'asymmetric',  # count=1
    'Under': 'asymmetric',  # count=1
    'UpgradeToEveryYear': 'asymmetric',  # count=1
    'Use': 'asymmetric',  # count=4
    'UseEfficiently': 'asymmetric',  # count=3
    'UseZipCode': 'asymmetric',  # count=1
    'Used': 'asymmetric',  # count=1
    'UsedBy': 'asymmetric',  # count=3
    'UsedFor': 'asymmetric',  # count=4
    'UsedIn': 'asymmetric',  # count=6
    'UsedWith': 'asymmetric',  # count=2
    'Uses': 'asymmetric',  # count=1
    'Value': 'asymmetric',  # count=1
    'VisitRegularly': 'asymmetric',  # count=1
    'VisitingProfessorAt': 'asymmetric',  # count=1
    'VisitingProfessorOf': 'asymmetric',  # count=1
    'WantToBeAddictedTo': 'asymmetric',  # count=2
    'WantToHelp': 'asymmetric',  # count=1
    'WantToWorkIn': 'asymmetric',  # count=1
    'WearEveryday': 'asymmetric',  # count=1
    'Win': 'asymmetric',  # count=1
    'WillingToSpendIn': 'asymmetric',  # count=2
    'Wins': 'asymmetric',  # count=2
    'With': 'asymmetric',  # count=5
    'Without': 'asymmetric',  # count=1
    'Won': 'asymmetric',  # count=5
    'WonAgainst': 'asymmetric',  # count=1
    'WonCup': 'asymmetric',  # count=1
    'WonPremierDivisionDuring': 'asymmetric',  # count=2
    'Work': 'asymmetric',  # count=1
    'WorkAt': 'asymmetric',  # count=4
    'WorkFor': 'asymmetric',  # count=3
    'WorkFrom': 'asymmetric',  # count=2
    'WorkIn': 'asymmetric',  # count=6
    'WorkWellInTeamsIn': 'asymmetric',  # count=2
    'WorkedWith': 'asymmetric',  # count=1
    'WorksAt': 'asymmetric',  # count=1
    'Write': 'asymmetric',  # count=1
    'Writes': 'asymmetric',  # count=1
    'WrittenBy': 'asymmetric',  # count=10
    'WrittenIn': 'asymmetric',  # count=2
    'Wrote': 'asymmetric',  # count=2,
}


# ── Helpers ──────────────────────────────────────────────────────────────────

def get_label(predicate_name: str) -> Label:
    """Look up an asymmetry label. Returns 'unknown' for predicates not
    present in the frozen table (post-freeze additions)."""
    return ASYMMETRY_LABELS.get(predicate_name, "unknown")


def asymmetry_axiom(predicate_name: str) -> Optional[str]:
    """Return the FOL witness axiom string for a binary predicate based
    on its label, or None for 'unknown' labels.

    Strict asymmetry: ``∀x,y.P(x,y) → ¬P(y,x)`` (forbids self-loops).
    Symmetry:        ``∀x,y.P(x,y) → P(y,x)``.

    The returned string follows the NLTK-compatible ASCII FOL surface
    syntax used elsewhere in SIV.
    """
    label = get_label(predicate_name)
    if label == "asymmetric":
        return f"all x.all y.({predicate_name}(x, y) -> -{predicate_name}(y, x))"
    if label == "symmetric":
        return f"all x.all y.({predicate_name}(x, y) -> {predicate_name}(y, x))"
    return None
